[package]
name = "syntax"
version = "0.1.0"
authors = ["Zachary Winter <plasticcaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
string_cache = "0.8"
